### ISSUE TITLE
Use AppBuilder methods for Gemfile and gitignore

### ISSUE THREAD

**Issue by gssbzn** [thoughtbot/suspenders#703] opened 2016-01-15 03:21 UTC
Is there a reason why [this](https://github.com/thoughtbot/suspenders/blob/master/lib/suspenders/app_builder.rb#L234):
```ruby
def replace_gemfile
  remove_file 'Gemfile'
  template 'Gemfile.erb', 'Gemfile'
end
```

Is preferred over this:
```ruby
def gemfile
  template "Gemfile.erb", "Gemfile"
end
```

Or [this](https://github.com/thoughtbot/suspenders/blob/master/lib/suspenders/app_builder.rb#L357):
```ruby
def gitignore_files
  remove_file '.gitignore'
  copy_file 'suspenders_gitignore', '.gitignore'
  ...
end
```
Over this:

```ruby
def gitignore
  copy_file "suspenders_gitignore", ".gitignore"
end
```

These changes will reduce I/O operations to disk but I don't know if this has been already discussed and discarded for some reason (I did a quick search of issues and couldn't find anything)

**Comment by tute** [comment] 2016-01-16 12:37
I can't think of any reason why we need the `remove_file` calls. It looks like @croaky introduced those lines; do you remember why/if we need them?

**Comment by tute** [comment] 2016-01-16 12:37
Thanks, @gssbzn, for showing us this!

**Comment by brandoncordell** [comment] 2016-01-17 09:08
The only thing I noticed by removing `remove_file 'Gemfile'` was the fact that I now get prompted to Overwrite the Gemfile when generating a new project.

![screen shot 2016-01-17 at 4 05 51 am](https://cloud.githubusercontent.com/assets/179822/12376691/a492fabe-bccf-11e5-96d0-4a5659645c51.png)

I can see as a user that might come off as an error or something that wasn't supposed to happen. I'm not sure if that was the reason for the change, just my two cents.

**Comment by gssbzn** [comment] 2016-01-17 14:12
My suggestion is to get rid of the `replace_gemfile` method and use the
`gemfile` inherited from AppBuilder. My concern is, if this will be
backward incompatible for some reason. There's also the template `force:
true` option so you don't get asked.
Right now I'm not able to do a proper PR but could do it later if these
changes are OK with the maintainers.

The only thing I noticed by removing remove_file 'Gemfile' was the fact
that I now get prompted to Overwrite the Gemfile when generating a new
project.

[image: screen shot 2016-01-17 at 4 05 51 am]
<https://cloud.githubusercontent.com/assets/179822/12376691/a492fabe-bccf-11e5-96d0-4a5659645c51.png>

I can see as a user that might come off as an error or something that
wasn't supposed to happen. I'm not sure if that was the reason for the
change, just my two cents.

—
Reply to this email directly or view it on GitHub
<https://github.com/thoughtbot/suspenders/issues/703#issuecomment-172302857>
.

**Comment by brandoncordell** [comment] 2016-01-17 20:22
Are you suggesting it'd be better to use `build :gemfile` inside of `app_generator.rb` or to rename `replace_gemfile` to `gemfile`?

Using `build :gemfile` doesn't work with the current setup because the inherited method uses `Gemfile` as the template (E.g. `template 'Gemfile'` instead of `template 'Gemfile.erb', 'Gemfile'`). Looks like we need the erb template because of the interpolation of the Ruby and Rails versions.

Oddly enough, if I just rename `replace_gemfile` to `gemfile`, I don't even have to use `force: true`. I'm not sure if that's the intended behavior but it seems to work and generate a project just fine that way.

**Comment by gssbzn** [comment] 2016-01-17 22:12
This is what I mean:
https://github.com/gssbzn/suspenders/blob/improve-gemfile-git-ignore/lib/suspenders/app_builder.rb#L23-L29

You don't need to call those methods on `AppGenerator`, they get called by default.
Like I said I'm happy to make a PR with those changes unless there's a reason (a problem I not aware of, backward incompatibility of some sort or something) preventing the use of the default Rails interface.

We can get a cleaner interface an less operations to disk from these changes.

**Comment by brandoncordell** [comment] 2016-01-17 22:19
:+1: 

That code looks great. I would support this for sure. Thanks @gssbzn for clarifying!

**Comment by tute** [comment] 2016-01-25 19:48
I'd love to test this in a PR. I am not aware if this was overlooked or indeed is guarding us from something, but we can easily test from a branch. Thanks for your input!

**Comment by tute** [comment] 2016-01-26 21:05
Thanks! Closing in favor of PR.

**Closed by tute** 2016-01-26 21:05 UTC
