### ISSUE TITLE
Fix dev:prime task on bin/setup script

### ISSUE THREAD

**Issue by LunaCodeGirl** [thoughtbot/suspenders#1068] opened 2021-04-19 14:46 UTC
When I install this gem and then, following the `README` run `bin/setup` I get the error:

> rails aborted!
Don't know how to build task 'dev:prime' (See the list of available tasks with `rails --tasks`)
/Users/luna/.gem/ruby/2.6.6/gems/railties-6.0.3.6/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/luna/.gem/ruby/2.6.6/gems/railties-6.0.3.6/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/luna/.gem/ruby/2.6.6/gems/railties-6.0.3.6/lib/rails/command.rb:48:in `invoke'
/Users/luna/.gem/ruby/2.6.6/gems/railties-6.0.3.6/lib/rails/commands.rb:18:in `<main>'
/Users/luna/.gem/ruby/2.6.6/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/luna/.gem/ruby/2.6.6/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/luna/.gem/ruby/2.6.6/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/luna/.gem/ruby/2.6.6/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/luna/.gem/ruby/2.6.6/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
[1]    60781 exit 1     bin/setup

**Comment by RasPat1** [comment] 2021-05-29 01:15
I'm having the same issue.

**Comment by thiagoa** [comment] 2022-06-10 15:30
It looks like the root cause of this error was that Suspenders wasn't aborting when something went wrong:

https://github.com/thoughtbot/suspenders/pull/1087

It would continue running the generators indefinitely and "hiding" environment errors in the `bin/suspenders` command output.

The above fix introduces better error reporting, and we'd get an explicit failure if it can't copy the `lib/tasks/dev.rake` file -- which would suggest what's wrong with our environment and allow us to fix any emerging issues.

Note that the latest fixes haven't been released to Rubygems yet, and we're in the process of fixing Suspenders' outstanding issues and getting the project up to date in general.

With that said, I'm closing this issue. Thank you @LunaCodeGirl !

**Closed by thiagoa** 2022-06-10 15:30 UTC
