### ISSUE TITLE
webpack.yml is missing after creating an app

### ISSUE THREAD

**Issue by naps62** [thoughtbot/suspenders#1059] opened 2020-11-09 10:43 UTC
After starting a new app (from suspenders 1.55.1), trying to start the server would fail because `config/webpack.yml` did not exist

Copying the default ones from a `rails new` app seemed to at least allow it to boot (haven't tested it the config works correctly)

**Comment by jsilasbailey** [comment] 2021-03-08 21:31
It seems that suspenders is not running the `webpacker:install` task when setting up the project. Since webpacker is used by default for Rails 6 on this should probably be run by default during the setup process. For now, rather than copying the yml file over, users of suspenders can run `bundle exec webpacker:install` in the app directory to set up webpacker ([documentation reference](https://github.com/rails/webpacker#installation)).

**Comment by jsilasbailey** [comment] 2021-03-26 17:07
From testing #1061 it seems that when that is merged this issue should be resolved

**Comment by thiagoa** [comment] 2021-10-01 22:43
Running suspenders under Rails 6.0.1.4 I'm unable to reproduce this problem. It may have happened that something failed along the way and suspenders was unable to get to the webpacker setup step (suspenders _should_ run `webpacker:install` if nothing goes wrong), which is among the last steps. 

This issue may have a relation with the following issue: 

https://github.com/thoughtbot/suspenders/issues/1080

That said, I'm closing this issue. Hopefully, by fixing some of the urgent issues we're facing this problem will become more visible and apparent, if it still exists.

Thank you @naps62 for reporting this issue ❤️

**Closed by thiagoa** 2021-10-01 22:43 UTC
