### ISSUE TITLE
Improve discoverability of generators

### ISSUE THREAD

**Issue by lancejjohnson** [thoughtbot/suspenders#1038] opened 2020-06-04 13:34 UTC
It is not immediately clear to infrequent users of suspenders how to use the gem after the initial project creation. I recently used suspenders to create a new Rails project and wanted to add the RSpec setup suspenders provides. My first thought was that it would be a Rake task. Not seeing suspenders-specific rake tasks available, I went to the repo to search for references to `rspec` in the project. Only then did I realize that there are generators provided by suspenders. Infrequent users of suspenders will benefit from more overt descriptions of the generators and how suspenders is useful beyond just the initial scaffolding of a project.

**Comment by mike-burns** [comment] 2020-06-08 15:39
This is great and we should do this.

Additionally, did you use the `suspenders` command-line tool to create the project (e.g. `suspenders my-totally-cool-project`)? That should have set up rspec for you.

**Comment by thiagoa** [comment] 2021-10-01 17:03
I have a hunch about what happened here. @lancejjohnson reported having used the Suspenders command-line tool, which should have installed RSpec by default. If it did not, the testing generator has probably failed to run for some reason. This error is documented here:

https://github.com/thoughtbot/suspenders/issues/1080

[When using suspenders with individual generators in a development environment](https://github.com/thoughtbot/suspenders/blob/d057894c05b66a8fea2249650aeb6c700fafe62a/GOALS.md) (which does not seem to be the case here), we should definitely make sure generators are properly documented and discoverable.

I will close this ticket in hopes that this issue will naturally be resolved as we progress with [our goals](https://github.com/thoughtbot/suspenders/blob/d057894c05b66a8fea2249650aeb6c700fafe62a/GOALS.md), but I suspect the root cause is documented in #1080. We can always reopen it if needed.

Thank you @lancejjohnson for reporting this issue! ❤️

**Closed by thiagoa** 2021-10-01 17:03 UTC
