### ISSUE TITLE
Doesn't work for ruby 2.6 (require ruby version 2.5.3)

### ISSUE THREAD

**Issue by dipto0321** [thoughtbot/suspenders#964] opened 2019-01-25 04:10 UTC
Default ruby version is 2.5.3. So that when I update to ruby 2.6.0 it's not run properly.

**Comment by dipto0321** [comment] 2019-01-26 09:51
When I run `suspenders projectname` It will cause an error because of gemfile ruby version. I'm using now ruby 2.6 but in gemfile default ruby version is 2.5.3. So that it stops the bundelling and not generate all the necessary files properly.

**Comment by composerinteralia** [comment] 2019-08-23 20:52
This seems like a duplicate of #871, so I am going to close this issue and continue tracking it on #871. Thanks!

**Closed by composerinteralia** 2019-08-23 20:52 UTC
