### ISSUE TITLE
Readme doesn't include delayed job migration

### ISSUE THREAD

**Issue by Danm72** [thoughtbot/suspenders#795] opened 2016-08-29 20:56 UTC
To run heroku local the delayed jobs table needs to be created

```rails g delayed_job:active_record```
```rake db:migrate```

**Comment by tute** [comment] 2016-08-31 01:31
When I generate a new 1.42 suspenders application, migrations are run and suspenders works well for me:

```
% suspenders -v
1.42.0
% suspenders test-795
[...]
         run  git init from "."
Initialized empty Git repository in /Users/tutec/Sites/opensource/suspenders/test-795/.git/
Setting up database
       force  config/database.yml
         run  bundle exec rake db:create db:migrate
Created database 'test-795_development'
Created database 'test-795_test'
W, [2016-08-30T21:28:52.599887 #15015]  WARN -- : [SKYLIGHT] [0.10.6] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
== 20160831012849 CreateDelayedJobs: migrating ================================
-- create_table(:delayed_jobs, {:force=>true})
   -> 0.0207s
-- add_index(:delayed_jobs, [:priority, :run_at], {:name=>"delayed_jobs_priority"})
   -> 0.0092s
== 20160831012849 CreateDelayedJobs: migrated (0.0301s) =======================
Creating local Heroku setup
[...]
% heroku local
[OKAY] Loaded ENV .env File as KEY=VALUE Format
9:30:05 PM web.1    |  [15681] Puma starting in cluster mode...
9:30:05 PM web.1    |  [15681] * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
9:30:05 PM web.1    |  [15681] * Min threads: 2, max threads: 2
9:30:05 PM web.1    |  [15681] * Environment: development
9:30:05 PM web.1    |  [15681] * Process workers: 1
9:30:05 PM web.1    |  [15681] * Preloading application
```

I'll close this issue as this is not a bug in suspenders. However, how did you generate the app to get the error?

Thanks!

**Closed by tute** 2016-08-31 01:31 UTC
