### ISSUE TITLE
Daemons gem for delayed_job

### ISSUE THREAD

**Issue by morenoh149** [thoughtbot/suspenders#545] opened 2015-03-24 08:56 UTC
I'm currently adding delayed job functionality to my app. One note, I had to add the 'daemons' gem to be able to run `bin/delayed_job` successfully. Might be good to add to this project.

**Comment by delphaber** [comment] 2015-03-25 10:12
I think that since thoughtbot use heroku, they use foreman and [this line in the Procfile](https://github.com/thoughtbot/suspenders/blob/master/templates/Procfile#L2) to run delayed job in a separate "worker"

But if you are not using heroku I think you really need `daemons` ! 

Could be pull request that add `daemons` if no `--heroku=true` welcome?

**Comment by morenoh149** [comment] 2015-03-25 10:19
Right! I later notice the call in the Procfile doesn't need the daemon gem installed.
Only if you want to run the project locally (without foreman) or on a non-heroku platform.
I actually kept the gem around because I like the more verbose output I can get from running `rails s`. Can I get that level of logging in the foreman output?

**Comment by delphaber** [comment] 2015-03-25 10:24
I think the problem is not in foreman but in unicorn
Webbrick (default `rails s` server) stdoutputs in development mode

I tried [this approach](http://dave.is/unicorn.html) once with  unicorn.

I don't know if it works nowadays :)

**Comment by tute** [comment] 2015-03-26 18:28
Thank you both for your input!

Closing this issue for now as it's not an issue with suspenders.

**Closed by tute** 2015-03-26 18:28 UTC
