### ISSUE TITLE
Missing bourbon gem?

### ISSUE THREAD

**Issue by lorentrogers** [thoughtbot/suspenders#789] opened 2016-07-17 20:01 UTC
A default install also seems to be missing the bourbon gem from the Gemfile. I had to manually update the `application.css` file to `application.scss`, remove the `*= require_tree .` Sprockets directive, then add in:
 
    @import "bourbon";                                                              
    @import "base/_base";

I'm running Debian 8.

**Comment by tute** [comment] 2016-07-20 01:16
Closing as duplicate of https://github.com/thoughtbot/suspenders/issues/787, to be fixed in https://github.com/thoughtbot/suspenders/pull/790. Thanks for reporting! :)

**Closed by tute** 2016-07-20 01:16 UTC
