### ISSUE TITLE
New project generation failing from Bourbon dependency

### ISSUE THREAD

**Issue by jakecraige** [thoughtbot/suspenders#805] opened 2016-11-04 15:47 UTC
Just tried to start a new project today and running into problems with the bourbon dependency. It just seems to die off at some point and doesn't continue.

```
/tmp $ suspenders -v
1.42.0
/tmp $ suspenders projectname
      create
      create  README.md
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/javascripts/application.js
      create  app/assets/javascripts/cable.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/assets/javascripts/channels
      create  app/assets/javascripts/channels/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/update
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/secrets.yml
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults.rb
      create  config/initializers/session_store.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  tmp
      create  tmp/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
      remove  config/initializers/cors.rb
   identical  Gemfile
      create  .ruby-version
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 11.3.0
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.4
Using addressable 2.4.0
Using execjs 2.7.0
Using awesome_print 1.7.0
Using babel-source 5.8.35
Using sass 3.4.22
Using thor 0.19.1
Using uniform_notifier 1.10.0
Using bundler 1.13.6
Using byebug 9.0.6
Using json 2.0.2
Using coderay 1.1.1
Using safe_yaml 1.0.4
Using database_cleaner 1.5.3
Using debug_inspector 0.0.2
Using diff-lcs 1.2.5
Using docile 1.1.5
Using dotenv 2.1.1
Using method_source 0.8.2
Using ffi 1.9.14
Using flutie 2.0.0
Using hashdiff 0.3.0
Using honeybadger 2.7.0
Using rb-fsevent 0.9.8
Using ruby_dep 1.5.0
Using normalize-rails 3.0.3
Using pg 0.19.0
Using slop 3.6.0
Using puma 3.6.0
Using rack-timeout 0.4.2
Using rails_stdout_logging 0.0.5
Using rspec-support 3.5.0
Using tilt 2.0.5
Using simplecov-html 0.10.0
Using timecop 0.8.1
Using tzinfo 1.2.2
Using nokogiri 1.6.8.1
Using rack-test 0.6.3
Using rack-mini-profiler 0.10.1
Using sprockets 3.7.0
Using websocket-driver 0.6.4
Using mime-types 3.1
Using launchy 2.4.3
Using rack-canonical-host 0.2.2
Using autoprefixer-rails 6.5.1.1
Using uglifier 3.0.3
Using babel-transpiler 0.7.0
Using bourbon 5.0.0.beta.7
Using bundler-audit 0.5.0
Using crack 0.4.3
Using rb-inotify 0.9.7
Using pry 0.10.4
Using rspec-core 3.5.4
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using simplecov 0.12.0
Using activesupport 5.0.0.1
Using loofah 2.0.3
Using xpath 2.0.0
Using mail 2.6.4
Using sprockets-es6 0.9.2
Using bitters 1.4.0
Using webmock 2.1.0
Using listen 3.1.5
Using pry-byebug 3.4.0
Using pry-rails 0.3.4
Using rails-dom-testing 2.0.1
Using globalid 0.3.7
Using activemodel 5.0.0.1
Using bullet 5.4.2
Using delayed_job 4.1.2
Using factory_girl 4.7.0
Using shoulda-matchers 3.1.1
Using skylight 1.0.0
Using spring 2.0.0
Using rails-html-sanitizer 1.0.3
Using capybara 2.7.1
Using recipient_interceptor 0.1.2
Using activejob 5.0.0.1
Using activerecord 5.0.0.1
Using spring-commands-rspec 1.0.4
Using actionview 5.0.0.1
Using capybara-webkit 1.11.1
Using formulaic 0.3.0
Using delayed_job_active_record 4.1.1
Using actionpack 5.0.0.1
Using actioncable 5.0.0.1
Using actionmailer 5.0.0.1
Using railties 5.0.0.1
Using sprockets-rails 3.2.0
Using simple_form 3.3.1
Using dotenv-rails 2.1.1
Using factory_girl_rails 4.7.0
Using jquery-rails 4.2.1
Using rspec-rails 3.5.2
Using web-console 3.4.0
Using rails 5.0.0.1
Using sass-rails 5.0.6
Using suspenders 1.42.0
Using title 0.0.7
Bundle complete! 42 Gemfile dependencies, 112 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
         run  bundle exec rails generate simple_form:install
W, [2016-11-04T08:45:44.143052 #62979]  WARN -- : [SKYLIGHT] [1.0.0] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
SimpleForm 3 supports Bootstrap and Zurb Foundation 5. If you want a configuration that is compatible with one of these frameworks, then please re-run this generator with --bootstrap or --foundation as an option.
      create  config/initializers/simple_form.rb
       exist  config/locales
      create  config/locales/simple_form.en.yml
      create  lib/templates/erb/scaffold/_form.html.erb
Setting up the development environment
      insert  config/environments/test.rb
      insert  config/environments/development.rb
      insert  config/environments/development.rb
      insert  config/application.rb
       force  bin/setup
         run  chmod a+x bin/setup from "."
      create  lib/tasks/dev.rake
      insert  config/application.rb
        gsub  config/environments/development.rb
        gsub  config/environments/test.rb
      insert  config/application.rb
Setting up the test environment
      create  spec/support/factory_girl.rb
      create  spec/factories.rb
      create  .hound.yml
    generate  rspec:install
W, [2016-11-04T08:45:46.752678 #62995]  WARN -- : [SKYLIGHT] [1.0.0] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
      create  .rspec
       exist  spec
      create  spec/spec_helper.rb
      create  spec/rails_helper.rb
      remove  spec/rails_helper.rb
      remove  spec/spec_helper.rb
      create  spec/rails_helper.rb
      create  spec/spec_helper.rb
         run  rails g delayed_job:active_record from "."
W, [2016-11-04T08:45:49.481019 #63018]  WARN -- : [SKYLIGHT] [1.0.0] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
      create  bin/delayed_job
       chmod  bin/delayed_job
      create  db/migrate/20161104154549_create_delayed_jobs.rb
      create  spec/support/database_cleaner.rb
      create  spec/support/shoulda_matchers.rb
      create  spec/features
      create  spec/features/.keep
      create  spec/support/features
      create  spec/support/features/.keep
      create  circle.yml
      create  spec/support/i18n.rb
      create  spec/support/action_mailer.rb
      create  spec/support/capybara_webkit.rb
Setting up the production environment
      create  config/smtp.rb
     prepend  config/environments/production.rb
      insert  config/environments/production.rb
      append  config/environments/production.rb
      insert  config/environments/production.rb
      insert  config/environments/production.rb
      insert  config/environments/production.rb
Moving secret token out of version control
       force  config/secrets.yml
Creating suspenders views
      create  app/views/application
      create  app/views/application/_flashes.html.erb
      create  app/helpers/flashes_helper.rb
      create  app/views/application/_javascript.html.erb
      create  app/views/application/_css_overrides.html.erb
       force  app/views/layouts/application.html.erb
Configuring app
      insert  config/environments/development.rb
      insert  config/environments/test.rb
      insert  config/environments/production.rb
      insert  config/application.rb
      insert  config/environments/test.rb
      remove  config/locales/en.yml
      create  config/locales/en.yml
      append  Rakefile
       force  config/puma.rb
      create  Procfile
      create  config/initializers/rack_mini_profiler.rb
Copying miscellaneous support files
      create  browserslist
      create  config/initializers/errors.rb
      create  config/initializers/json_encoding.rb
Customizing the 500/404/422 pages
      insert  public/500.html
      insert  public/404.html
      insert  public/422.html
       exist
      create  .ctags
      create  .env
Initializing git
      create  app/views/pages
      create  app/views/pages/.keep
      create  spec/lib
      create  spec/lib/.keep
      create  spec/controllers
      create  spec/controllers/.keep
      create  spec/helpers
      create  spec/helpers/.keep
      create  spec/support/matchers
      create  spec/support/matchers/.keep
      create  spec/support/mixins
      create  spec/support/mixins/.keep
      create  spec/support/shared_examples
      create  spec/support/shared_examples/.keep
         run  git init from "."
Initialized empty Git repository in /private/tmp/projectname/.git/
Setting up database
       force  config/database.yml
         run  bundle exec rake db:create db:migrate
Created database 'projectname_development'
Created database 'projectname_test'
W, [2016-11-04T08:45:52.765987 #63043]  WARN -- : [SKYLIGHT] [1.0.0] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
== 20161104154549 CreateDelayedJobs: migrating ================================
-- create_table(:delayed_jobs, {:force=>true})
   -> 0.0057s
-- add_index(:delayed_jobs, [:priority, :run_at], {:name=>"delayed_jobs_priority"})
   -> 0.0022s
== 20161104154549 CreateDelayedJobs: migrated (0.0081s) =======================

Creating local Heroku setup
      create  bin/setup_review_app
         run  chmod a+x bin/setup_review_app from "."
      create  bin/deploy
      append  README.md
         run  chmod a+x bin/deploy from "."
      create  app.json
Setting up Segment
      create  app/views/application/_analytics.html.erb
Setting up bundler-audit
      create  lib/tasks/bundler_audit.rake
      append  Rakefile
Springifying binstubs
         run  bundle exec spring binstub --all
* bin/rake: spring inserted
* bin/rspec: generated with spring
* bin/rails: spring inserted
         run  spring stop from "."
Spring is not running
    generate  suspenders:static
W, [2016-11-04T08:45:56.571491 #63073]  WARN -- : [SKYLIGHT] [1.0.0] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
Running via Spring preloader in process 63094
     gemfile  high_voltage
         run  bundle install from "."
Resolving dependencies...
Using rake 11.3.0
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.4
Using addressable 2.4.0
Using execjs 2.7.0
Using awesome_print 1.7.0
Using babel-source 5.8.35
Using sass 3.4.22
Using thor 0.19.1
Using uniform_notifier 1.10.0
Using bundler 1.13.6
Using byebug 9.0.6
Using json 2.0.2
Using coderay 1.1.1
Using safe_yaml 1.0.4
Using database_cleaner 1.5.3
Using debug_inspector 0.0.2
Using diff-lcs 1.2.5
Using docile 1.1.5
Using dotenv 2.1.1
Using method_source 0.8.2
Using ffi 1.9.14
Using flutie 2.0.0
Using hashdiff 0.3.0
Using high_voltage 3.0.0
Using honeybadger 2.7.0
Using rb-fsevent 0.9.8
Using ruby_dep 1.5.0
Using normalize-rails 3.0.3
Using pg 0.19.0
Using slop 3.6.0
Using puma 3.6.0
Using rack-timeout 0.4.2
Using rails_stdout_logging 0.0.5
Using rspec-support 3.5.0
Using tilt 2.0.5
Using simplecov-html 0.10.0
Using timecop 0.8.1
Using tzinfo 1.2.2
Using nokogiri 1.6.8.1
Using rack-test 0.6.3
Using rack-mini-profiler 0.10.1
Using sprockets 3.7.0
Using websocket-driver 0.6.4
Using mime-types 3.1
Using launchy 2.4.3
Using rack-canonical-host 0.2.2
Using autoprefixer-rails 6.5.1.1
Using uglifier 3.0.3
Using babel-transpiler 0.7.0
Using bourbon 5.0.0.beta.7
Using bundler-audit 0.5.0
Using crack 0.4.3
Using rb-inotify 0.9.7
Using pry 0.10.4
Using rspec-core 3.5.4
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using simplecov 0.12.0
Using activesupport 5.0.0.1
Using loofah 2.0.3
Using xpath 2.0.0
Using mail 2.6.4
Using sprockets-es6 0.9.2
Using bitters 1.4.0
Using webmock 2.1.0
Using listen 3.1.5
Using pry-byebug 3.4.0
Using pry-rails 0.3.4
Using rails-dom-testing 2.0.1
Using globalid 0.3.7
Using activemodel 5.0.0.1
Using bullet 5.4.2
Using delayed_job 4.1.2
Using factory_girl 4.7.0
Using shoulda-matchers 3.1.1
Using skylight 1.0.0
Using spring 2.0.0
Using rails-html-sanitizer 1.0.3
Using capybara 2.7.1
Using recipient_interceptor 0.1.2
Using activejob 5.0.0.1
Using activerecord 5.0.0.1
Using spring-commands-rspec 1.0.4
Using actionview 5.0.0.1
Using capybara-webkit 1.11.1
Using formulaic 0.3.0
Using delayed_job_active_record 4.1.1
Using actionpack 5.0.0.1
Using actioncable 5.0.0.1
Using actionmailer 5.0.0.1
Using railties 5.0.0.1
Using sprockets-rails 3.2.0
Using simple_form 3.3.1
Using dotenv-rails 2.1.1
Using factory_girl_rails 4.7.0
Using jquery-rails 4.2.1
Using rspec-rails 3.5.2
Using web-console 3.4.0
Using rails 5.0.0.1
Using sass-rails 5.0.6
Using suspenders 1.42.0
Using title 0.0.7
Bundle complete! 43 Gemfile dependencies, 113 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
    generate  suspenders:stylesheet_base
Running via Spring preloader in process 63121
     gemfile  bourbon (5.0.0.beta.6)
     gemfile  neat (~> 1.8.0)
     gemfile  refills
         run  bundle install from "."
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
You have requested:
  bourbon = 5.0.0.beta.6

The bundle currently has bourbon locked at 5.0.0.beta.7.
Try running `bundle update bourbon`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
      create  app/assets/stylesheets/application.scss
      remove  app/assets/stylesheets/application.css
    generate  refills:import
You have requested:
  bourbon = 5.0.0.beta.6

The bundle currently has bourbon locked at 5.0.0.beta.7.
Try running `bundle update bourbon`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
Run `bundle install` to install missing gems.
      remove  app/views/refills
         run  bitters install --path app/assets/stylesheets from "."
You have requested:
  bourbon = 5.0.0.beta.6

The bundle currently has bourbon locked at 5.0.0.beta.7.
Try running `bundle update bourbon`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
Run `bundle install` to install missing gems.
Congratulations! You just pulled our suspenders.
Run 'bundle exec honeybadger heroku install' with your API key.
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
You have requested:
  bourbon = 5.0.0.beta.6

The bundle currently has bourbon locked at 5.0.0.beta.7.
Try running `bundle update bourbon`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
         run  bundle exec spring binstub --all
You have requested:
  bourbon = 5.0.0.beta.6

The bundle currently has bourbon locked at 5.0.0.beta.7.
Try running `bundle update bourbon`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
Run `bundle install` to install missing gems.
```

Any ideas?

**Comment by tute** [comment] 2016-11-04 15:51
Relevant error message:

```
You have requested:
  bourbon = 5.0.0.beta.6

The bundle currently has bourbon locked at 5.0.0.beta.7.
Try running `bundle update bourbon`
```

cc @tysongach

**Comment by tysongach** [comment] 2016-11-04 15:54
@jakecraige Is this from Suspenders `master`? Or `1.42.0`?

Teo and I were _just_ experiencing this.

**Comment by jakecraige** [comment] 2016-11-04 16:05
@tysongach 1.42.0

**Comment by tysongach** [comment] 2016-11-04 18:28
I believe I’ve tracked down the issue, with the help of @teoljungberg.

- Bitters is a [dependency in the Suspenders gem](https://github.com/thoughtbot/suspenders/blob/master/suspenders.gemspec#L30).
- Before Suspenders runs its `stylesheet_base` generator, Bitters gets installed, and it is currently installing `1.4`.
- Bitters `1.4` [specifies Bourbon as a dependency](https://github.com/thoughtbot/bitters/blob/master/bitters.gemspec#L10).
- With its current spec (`"bourbon", ">= 5.0.0.beta.6"`), Bitters `1.4` is coming with Bourbon `5.0.0.beta.7`.
- The problem is the `stylesheet_base` generator gets runs later in the Suspenders build process, and **in version `1.42.0` it is [specifying a hard lock on Bourbon `5.0.0.beta.6`](https://github.com/thoughtbot/suspenders/blob/v1.42.0/lib/suspenders/generators/stylesheet_base_generator.rb#L10).
- Since Beta 7 is already packaged with Bitters, the `stylesheet_base` generator then fails.

So two things to fix:

1. I’ve already merged into `master` (yesterday) an upgrade to Bourbon `5.0.0.beta.7` for Suspenders, so we should cut that release.
2. I will also put a PR to Bitters to lock down the Beta version, instead of mapping to a `>=` version specifier. We can then better coordinate our releases in the future.

**Comment by tysongach** [comment] 2016-11-04 18:53
_Or_…should loosen the version specifier is Suspenders?

So, `gem "bourbon", "5.0.0.beta.6"` in the `stylesheet_base` generator matches what Bitters specifies (`gem "bourbon", ">= 5.0.0.beta.6"`)?

**Comment by tysongach** [comment] 2016-11-07 18:51
Ping @tute. Any thoughts on the above?

**Comment by tute** [comment] 2016-11-07 18:59
I am not deep into the details of how our frontend pieces fit together or their release timelines yet to provide a definitive answer yet. In general, loosening dependency version requirements makes for easier to setup projects.

Two questions: Would `>=` work after we release 5.0? Does this problem arise because we are using beta versions, that don't play along with each other nicely?

We can chat in person too! :)

**Comment by tysongach** [comment] 2016-11-07 21:09
I’ve put up a PR to Bitters to loosen the version specifier: https://github.com/thoughtbot/bitters/pull/264

And done the same here on Suspenders: https://github.com/thoughtbot/suspenders/pull/806

**Closed** 2016-11-08 00:30 UTC

**Comment by tysongach** [comment] 2016-11-09 13:28
@jakecraige Do you want to try v1.43 and see if your issue is indeed fixed?

**Comment by jakecraige** [comment] 2016-11-09 21:47
@tysongach looks good! 👍
