### ISSUE TITLE
Uses sprockets-es6 - Causes deprecation warnings.

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/suspenders#793] opened 2016-07-25 18:43 UTC
sprockets-es6 is causing depreciation issues for Sprockets, and the gem author says that the gem will never reach v1.0.  May I ask how this gem is being used?

**Comment by tute** [comment] 2016-07-25 18:44
Related with https://github.com/thoughtbot/suspenders/issues/726

**Comment by tute** [comment] 2016-08-09 18:55
@ACPK: while sprockets 4 is not released, what is a good alternative? Cc @MattMSumner 

Thanks!

**Comment by MattMSumner** [comment] 2016-08-10 19:35
https://github.com/browserify-rails/browserify-rails seems like a possibility. @BlakeWilliams do you have any thoughts on alternative approaches?

**Comment by MattMSumner** [comment] 2016-08-10 19:42
@ACPK to answer your question, the gem is being used to allow writing ES6. The javascript community as a whole has moved towards using transpilers, such as [babel](https://babeljs.io), to get access to features we've come to expect of a modern programming language. In the past, we have used coffeescript to fill in the gaps we've had with ES5 but I've found that coffeescript has stopped moving forward while ES6 promises to provide all the features we're looking for without significantly changing the syntax, in a forwards compatible way.

I introduced sprockets-es6 to go along with [this PR](https://github.com/thoughtbot/guides/pull/387) on our guides.

**Comment by MattMSumner** [comment] 2016-08-10 19:54
Here's the issue on sprockets 4.0 milestone around babel and javascript modules https://github.com/rails/sprockets/issues/73

**Comment by tute** [comment] 2016-08-31 01:32
sprockets v4 beta3 recently released: https://github.com/rails/sprockets/releases/tag/v4.0.0.beta3

**Comment by tute** [comment] 2016-08-31 02:00
Closing as duplicate of https://github.com/thoughtbot/suspenders/issues/726. Soon we'll add `babel-transpiler` and `sprockets` 4 (I'm not against doing it while it's still in beta).
Thanks!

**Closed by tute** 2016-08-31 02:00 UTC
