### ISSUE TITLE
Sass::Syntax error at @import "refills/flashes"

### ISSUE THREAD

**Issue by ryanwaits** [thoughtbot/suspenders#769] opened 2016-05-22 17:25 UTC
Unable to import ```'refills/flashes'``` when running ```rspec```

    ActionView::Template::Error:
       File to import not found or unreadable: refills/flashes.
       Load paths:
         /Users/ryanwaits/.rvm/gems/ruby-2.3.0/gems/babel-source-5.8.35/lib
         /Users/ryanwaits/Code/projects/paste_bin/app/assets/images
         /Users/ryanwaits/Code/projects/paste_bin/app/assets/javascripts
         /Users/ryanwaits/Code/projects/paste_bin/app/assets/stylesheets
         /Users/ryanwaits/Code/projects/paste_bin/vendor/assets/javascripts
         /Users/ryanwaits/Code/projects/paste_bin/vendor/assets/stylesheets
         /Users/ryanwaits/.rvm/gems/ruby-2.3.0/gems/normalize-rails-3.0.3/vendor/assets/stylesheets
         /Users/ryanwaits/.rvm/gems/ruby-2.3.0/gems/neat-1.7.4/app/assets/stylesheets
         /Users/ryanwaits/.rvm/gems/ruby-2.3.0/gems/jquery-rails-4.1.1/vendor/assets/javascripts
         /Users/ryanwaits/.rvm/gems/ruby-2.3.0/gems/bourbon-5.0.0.beta.5/core
     # ./app/assets/stylesheets/application.scss:9

    # --- Caused by: ---
     # Sass::SyntaxError:

**Comment by teoljungberg** [comment] 2016-05-23 14:30
Related to #476

**Comment by tute** [comment] 2016-06-25 16:00
Closing as duplicate of https://github.com/thoughtbot/suspenders/issues/779. Thanks for your report!

**Closed** 2016-06-25 16:01 UTC
