### ISSUE TITLE
rails_helper

### ISSUE THREAD

**Issue by kvokka** [thoughtbot/suspenders#721] opened 2016-02-26 05:55 UTC
Hello,
actually I do not know, is it a bug or a feature, and I did not found better way, than write here.
There is no any mention of `spec_helper` in `rails_helper`, and if use config as usual, including only `rails-helper` in specs, you will never achieve `simplecov`.
I understand, that there may me any reason to move in other file `webmock`s, but why `expect` syntax and `simplecov` are moved also?
I will be very pleased, if you will say me the core of the idea of this feature, or give some data about it.
Thank you!

**Comment by tute** [comment] 2016-03-03 02:14
> There is no any mention of `spec_helper` in `rails_helper` [...] you will never achieve simplecov.

As https://github.com/thoughtbot/suspenders/issues/631 shows, suspenders apps generate a `.rspec` file which includes spec_helper, and thus we get coverage.

> why expect syntax and simplecov are moved also?

I don't understand this question. Can you please explain more?

---

I will close this issue as it's not a bug in suspenders, but I'm happy to continue this thread. Thanks!

**Closed by tute** 2016-03-03 02:14 UTC
